#include "hardware.h"
#include "util.h"

#define DEFINE_SEGMENT

#define SEGMENT_CENTER SHIFT(0)
#define SEGMENT_TOPLEFT SHIFT(1)
#define SEGMENT_BOTTOMLEFT SHIFT(2)
#define SEGMENT_BOTTOM SHIFT(3)
#define SEGMENT_TOPRIGHT SHIFT(4)
#define SEGMENT_BOTTOMRIGHT SHIFT(5)
#define SEGMENT_TOP SHIFT (6)

#define D0 SEGMENT_TOP | SEGMENT_TOPLEFT | SEGMENT_BOTTOMLEFT | SEGMENT_BOTTOM | SEGMENT_BOTTOMRIGHT | SEGMENT_TOPRIGHT
#define D1 SEGMENT_TOPRIGHT | SEGMENT_BOTTOMRIGHT
#define D2 SEGMENT_TOP | SEGMENT_TOPRIGHT | SEGMENT_CENTER | SEGMENT_BOTTOMLEFT | SEGMENT_BOTTOM
#define D3 SEGMENT_TOP | SEGMENT_TOPRIGHT | SEGMENT_CENTER | SEGMENT_BOTTOMRIGHT | SEGMENT_BOTTOM
#define D4 SEGMENT_TOPLEFT | SEGMENT_CENTER | SEGMENT_TOPRIGHT | SEGMENT_BOTTOMRIGHT
#define D5 SEGMENT_TOP | SEGMENT_TOPLEFT | SEGMENT_CENTER | SEGMENT_BOTTOMRIGHT | SEGMENT_BOTTOM
#define D6 SEGMENT_TOP | SEGMENT_TOPLEFT | SEGMENT_CENTER | SEGMENT_BOTTOMLEFT | SEGMENT_BOTTOM | SEGMENT_BOTTOMRIGHT
#define D7 SEGMENT_TOP | SEGMENT_TOPRIGHT | SEGMENT_BOTTOMRIGHT
#define D8 D0 | SEGMENT_CENTER
#define D9 SEGMENT_TOP | SEGMENT_TOPLEFT | SEGMENT_CENTER | SEGMENT_TOPRIGHT | SEGMENT_BOTTOMRIGHT

void convertValueToSegments(number value, segment segments[], uint8_t size)  ;